# Installing 7zip

- name: download 7zip
  get_url:
    url: "{{ item }}"
    dest: "{{ remote_install_path }}"
  with_items:
    - https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-16.02-10.el7.x86_64.rpm
    - https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/p7zip-plugins-16.02-10.el7.x86_64.rpm

- name: Install 7zip package
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - p7zip-16.02-10.el7.x86_64.rpm
    - p7zip-plugins-16.02-10.el7.x86_64.rpm
  become: yes
