# Installing MAYA
# Should be on the nfs mount, if not add a task to copy the files, e.g.
## - name: Copy sen2agri install files
##   copy:
##     src: "{{ your local path }}/Maja_3.2.2_TM.zip
##     dest: "{{ remote_install_path }}"

- name: create folder for sen2agri and maja unzipped files
  file:
    path: "{{ remote_install_path }}/Sen2AgriDistribution/maja"
    state: directory
    mode: '0774'

- name: Extract gipp-MAJA package
  shell: 7z x {{ remote_install_source }}/Sen2Agri-gipp-maja-3.2.2.zip -o{{ remote_install_path }}/Sen2AgriDistribution -y
  become_user: sen2agri-service

- name: Extract MAJA package
  shell: 7z x {{ remote_install_source }}/Maja_3.2.2_TM.zip -o{{ remote_install_path }}/Sen2AgriDistribution/maja/ -y


### Not required, conflicts with the install script
#- name: install MAJA
#  shell: bash {{ remote_install_path }}/Sen2AgriDistribution/maja/Maja-3.2.2-TM/MAJA-3.2.2_TM.run --target /opt/maja
#  become: yes
