# Setup Server for sen2agri services
- hosts: sen2agri
  roles:
    - 7zip
    - nfs-mount
    - maja
    - sen2agri
    - git
    - python3
  vars:
    sen2agri_version: "2.0.2"
    remote_install_path: "/home/cloud/sen2agri-{{ sen2agri_version }}"
    remote_install_source: "/mnt/openforecast-runner/sen2Agri/s2a_setup"
    db_name: "sen2agri"
    db_host: "***"
    db_port: "5432"
    db_user: "admin"
    db_pass: "***"
    sen2agri_group: "USER_GROUP"
    sen2agri_group_gid: "5200"
    sen2agri_groups: "USER_GROUP2"
    sen2agri_groups_gid: "5202"
    nfs_src: "***"
    nfs_path: "/mnt/sen2agri-data"
    nfs_user: "sen2agri-user"
    nfs_user_uid: "***"
